# root: true

# parser: babel-eslint

# extends:
#   - airbnb
#   - plugin:react/recommended

# plugins:
#   - react
#   - import

# env:
#   es6: true
#   browser: true
#   node: true

# parserOptions:
#   ecmaVersion: 6
#   sourceType: module
#   ecmaFeatures:
#     jsx: true

# rules:
#   react/jsx-filename-extension: off
#   react/no-danger: off
#   camelcase: off
#   max-len: [warn, { 'code': 90 }]
#   no-console: off
#   jsx-a11y/anchor-is-valid: off